# Generated by Django 5.2.4 on 2025-08-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_plan', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_allowed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.TextField(blank=True, null=True)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_plan.budgetplan')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
