# Generated by Django 5.2.4 on 2025-08-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_item', '0001_initial'),
        ('budget_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='budget_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget_plan.budgetplan'),
        ),
    ]
