# Generated by Django 5.2.4 on 2025-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
