# Generated by Django 5.2.4 on 2025-08-12 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_item', '0002_alter_budgetitem_budget_plan'),
        ('budget_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.TextField(blank=True, null=True)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_plan.budgetplan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_item.budgetitem')),
            ],
        ),
    ]
